### PR TITLE
[#30] Fix not found responses

### LINKED ISSUE #30: "400 bad request" is returned for non-existing objects instead of 404
```
$ LANG=C wget http://localhost:8082/get/Dxhf4PNprrJHWWTG5RGLdfLkJiSQ3AQqit1MSnEPRkDZ/Dinq6fbQR9Ry1NQvp4YzmTgDXCQ5SYQ9FR7koyTFjb2a
--2021-04-30 00:19:35--  http://localhost:8082/get/Dxhf4PNprrJHWWTG5RGLdfLkJiSQ3AQqit1MSnEPRkDZ/Dinq6fbQR9Ry1NQvp4YzmTgDXCQ5SYQ9FR7koyTFjb2a
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:8082... failed: Connection refused.
Connecting to localhost (localhost)|127.0.0.1|:8082... connected.
HTTP request sent, awaiting response... 400 Bad Request
2021-04-30 00:19:35 ERROR 400: Bad Request.
```
Gate log:
```
2021-04-30T00:19:35.457+0300    error   downloader/download.go:104      could not receive object        {"cid": "Dxhf4PNprrJHWWTG5RGLdfLkJiSQ3AQqit1MSnEPRkDZ", "oid": "Dinq6fbQR9Ry1NQvp4YzmTgDXCQ5SYQ9FR7koyTFjb2a", "elapsed": "63.078586ms", "error": "reading the response failed: rpc error: code = Unknown desc = object not found", "errorVerbose": "rpc error: code = Unknown desc = object not found\nreading the response failed\ngithub.com/nspcc-dev/neofs-api-go/pkg/client.(*clientImpl).GetObject\n\tgithub.com/nspcc-dev/neofs-api-go@v1.25.0/pkg/client/object.go:542\ngithub.com/nspcc-dev/neofs-http-gate/neofs.(*neofsObjectClient).Get\n\tgithub.com/nspcc-dev/neofs-http-gate/neofs/client-plant.go:128\ngithub.com/nspcc-dev/neofs-http-gate/downloader.(*request).receiveFile\n\tgithub.com/nspcc-dev/neofs-http-gate/downloader/download.go:102\ngithub.com/nspcc-dev/neofs-http-gate/downloader.(*Downloader).DownloadByAddress\n\tgithub.com/nspcc-dev/neofs-http-gate/downloader/download.go:214\ngithub.com/fasthttp/router.(*Router).Handler\n\tgithub.com/fasthttp/router@v1.3.5/router.go:414\ngithub.com/valyala/fasthttp.(*Server).serveConn\n\tgithub.com/valyala/fasthttp@v1.22.0/server.go:2219\ngithub.com/valyala/fasthttp.(*workerPool).workerFunc\n\tgithub.com/valyala/fasthttp@v1.22.0/workerpool.go:223\ngithub.com/valyala/fasthttp.(*workerPool).getCh.func1\n\tgithub.com/valyala/fasthttp@v1.22.0/workerpool.go:195\nruntime.goexit\n\truntime/asm_amd64.s:1371"}
```
The problem is that even though `desc` has proper `object not found` string the `code` is `Unknown` and thus we return this generic error 400 instead of more appropriate 404. I'm not sure this happens and it doesn't seem to be critical, but maybe @alexvanin knows something about it (we're doing a `GetObject` call here (`WithAddress/WithSession/WithBearer`)).

### PR DESCRIPTION
**Pull request by KirillovDenis**
closes #30 

Signed-off-by: Denis Kirillov <denis@nspcc.ru>

### CODE REVIEW

File: downloader/download.go [hunk 1]
```diff
@@ -210,12 +208,13 @@ func (r *request) handleNeoFSErr(err error, start time.Time) {
...
 		cause = unwrap
 	}
-	if st, ok := status.FromError(cause); ok && st != nil {
-		if st.Code() == codes.NotFound {
-			code = fasthttp.StatusNotFound
-		}
-		msg = st.Message()
+
+	if strings.Contains(cause.Error(), "not found") ||
+		strings.Contains(cause.Error(), "can't fetch container info") {
```
Comment (roman-khimov) [inline downloader/download.go:213]: String matching is fragile of course, but still better than current status-quo.

**Review by masterSplinter01 — APPROVED** [review]

**Review by alexvanin — APPROVED** [review]
