### PR TITLE
[#11] Fix headers format

### LINKED ISSUE #111: System headers response format
Currently using `http-gw` we can set expiration epoch using header `X-Attribute-Neofs-Expiration-Epoch`.
But when we get object the header will be `X-Attribute-__NEOFS__EXPIRATION_EPOCH`. Shouldn't we change this behavior?

### PR DESCRIPTION
**Pull request by masterSplinter01**
Closes #111

Also moved attribute/headers constants to a separate file `util/attributes.go`. I'm not sure that the name is correct/good enough,  but I have no better idea about the name.

### CODE REVIEW

File: downloader/download.go [hunk 1]
```diff
@@ -171,9 +181,9 @@ func (r request) receiveFile(clnt pool.Object, objectAddress *object.Address) {
 			contentType = val
 		}
 	}
-	r.Response.Header.Set("x-object-id", obj.ID().String())
-	r.Response.Header.Set("x-owner-id", obj.OwnerID().String())
-	r.Response.Header.Set("x-container-id", obj.ContainerID().String())
+	r.Response.Header.Set("X-Object-Id", obj.ID().String())
+	r.Response.Header.Set("X-Owner-Id", obj.OwnerID().String())
+	r.Response.Header.Set("X-Container-Id", obj.ContainerID().String())
```
Comment (realloc) [inline downloader/download.go:186]: 👍🏻

File: downloader/download.go [hunk 2]
```diff
@@ -45,7 +46,13 @@ type (
 	}
 )
 
-var errObjectNotFound = errors.New("object not found")
+var (
+	errObjectNotFound = errors.New("object not found")
+
+	exceptionWords = map[string]struct{}{
+		"RFC3339": {},
```
Comment (KirillovDenis) [inline downloader/download.go:53]: I'm not sure we need this. Any of this headers:
1. `X-Attribute-Neofs-Expiration-Epoch`
2. `X-Attribute-Neofs-Expiration-Duration`
3. `X-Attribute-Neofs-Expiration-Timestamp`
4. `X-Attribute-Neofs-Expiration-RFC3339`

will be translate to `__NEOFS__EXPIRATION_EPOCH` attribute for neofs object. So if `RFC3339` exception word appeared due using `X-Attribute-Neofs-Expiration-RFC3339` header while object uploading we can omit it

Comment (masterSplinter01) [reply downloader/download.go]: You're right forgot to remove it.. Fixed

**Review by KirillovDenis — APPROVED** [review]

**Review by alexvanin — APPROVED** [review]
