### PR TITLE
[#94] Fix multiple testcontainer images

### LINKED ISSUE #94: Support multiple testcontainer images
We have seen an issue when running tests on multiple testcontainer images. First testcontainer image processed correctly but second one is not starting and we get timeout error.

```
        	Error:      	Received unexpected error:
        	            	context deadline exceeded
        	            	failed to start container
        	            	github.com/testcontainers/testcontainers-go.GenericContainer
```

There are some weird things I see:
1. Second image fails with https://github.com/nspcc-dev/neofs-node/issues/934 error. Maybe this fix will be enough to solve the issue.
2. I tried to replace host networking of testcontainers with port forwarding, however neofs-node was not ready for RPC communication, even though it considered to be heatlhy. In docker logs I see these records in wrong order but maybe it is just output issue:
```
aio container started
/bin/neofs-node --config /config/config-sn.yaml
```
3. `cancel()` function does not stop http-gw immediately. It takes about 10 seconds before we can see shutdown message in logs, which is a bit longer then I would expect.

4. Maybe using subtest runs with `t.Run` is not that great because we can't control the order, tests can be parallelized and all sort of things. No strong opinion on that.

### PR DESCRIPTION
**Pull request by KirillovDenis**
closes #94 

Signed-off-by: Denis Kirillov <denis@nspcc.ru>

### CODE REVIEW

File: integration_test.go [hunk 1]
```diff
@@ -35,11 +35,13 @@ type putResponse struct {
 func TestIntegration(t *testing.T) {
 	ctx := context.Background()
 	aioImage := "nspccdev/neofs-aio-testcontainer:"
-	versions := []string{"latest"}
+	versions := []string{"0.24.0", "0.25.1", "latest"}
 	key, err := keys.NewPrivateKeyFromHex("1dd37fba80fec4e6a6f13fd708d8dcb3b29def768017052f6c930fa1c5d90bbb")
 	require.NoError(t, err)
 
 	for _, version := range versions {
+		ctx, cancel2 := context.WithCancel(ctx)
```
Comment (alexvanin) [inline integration_test.go:43]: Shading of `ctx` looks not so good in `for` cycle. I propose to use different context name.

```suggestion
		cctx, cancel2 := context.WithCancel(ctx)
```

**Review by alexvanin — APPROVED** [review]
