### PR TITLE
[#144] Add more verbose error output

### LINKED ISSUE #144: Need more details when `could not store file in neofs` error occures
```
$ curl -F 'file=@/tmp/upload/object.sample;filename=upload/object.sample' http://host/upload/CnboFmktZY9a2i6KeSTZ8b6Vf94xfaaTF9vzpcqQBBYM
could not store file in neofs
```
Would you please provide additional information on error cause?

Upon the failed request, the error in neofs-http-gw log was
```
апр 18 11:36:06 az neofs-http[43648]: 2022-04-18T11:36:06.428Z        error        uploader/upload.go:143        could not store file in neofs        {"cid": "CnboFmktZY9a2i6KeSTZ8b6Vf94xfaaTF9vzpcqQBBYM", "error": "client failure: write request: EOF"}
```

### PR DESCRIPTION
**Pull request by KirillovDenis**
closes #144 
Signed-off-by: Denis Kirillov <denis@nspcc.ru>

### CODE REVIEW

File: uploader/upload.go [hunk 1]
```diff
@@ -95,12 +95,12 @@ func (u *Uploader) Upload(c *fasthttp.RequestCtx) {
 		epochDuration, err := getEpochDurations(c, u.pool)
 		if err != nil {
 			log.Error("could not get epoch durations from network info", zap.Error(err))
-			response.Error(c, "could parse expiration header, try expiration in epoch", fasthttp.StatusBadRequest)
+			response.Error(c, "could not get epoch durations from network info: "+err.Error(), fasthttp.StatusBadRequest)
 			return
 		}
 		if err = prepareExpirationHeader(filtered, epochDuration); err != nil {
 			log.Error("could not prepare expiration header", zap.Error(err))
```
Comment (alexvanin) [inline uploader/upload.go:102]:
```suggestion
			log.Error("could not parse expiration header", zap.Error(err))
```

**Review by alexvanin — APPROVED** [review]

**Review by masterSplinter01 — APPROVED** [review]
